#ifndef MC_JSON_TYPES_H
#define MC_JSON_TYPES_H

/*
 types
*/
typedef enum {
 MJS_TYPE_STRING = 1,
 MJD_TYPE_BOOLEAN = 2,
 MJS_TYPE_NULL = 3,
 MJS_TYPE_OBJECT = 4,
 MJS_TYPE_ARRAY = 5,
 MJS_TYPE_NUMBER_INT = 6,
 MJS_TYPE_NUMBER_FLOAT = 7,
} MJS_TYPE;

/*
 error defs
*/
typedef enum {
 MJS_RESULT_NO_ERROR = 0,
 MJS_RESULT_NULL_POINTER = -1,
 MJS_RESULT_SYNTAX_ERROR = -2,
 MJS_RESULT_UNEXPECTED_TOKEN = -3,
 MJS_RESULT_INCOMPLETE_BRACKETS = -4,
 MJS_RESULT_INCOMPLETE_DOUBLE_QUOTES = -5,
 MJS_RESULT_ALLOCATION_FAILED = -6,
 MJS_RESULT_INVALID_TYPE = -7,
 MJS_RESULT_REACHED_MAX_NESTED_DEPTH = -8,
} MJS_RESULT;

/*
 limits
*/
#define MAX_CACHE_BYTES      512
#define MAX_RESERVE_BYTES    128
#define MAX_RESERVE_ELEMENTS 16
#define MAX_NESTED_VALUE     10
#define MAX_HASH_BUCKETS     16

#endif

