#ifndef MC_JSON_TYPES_H
#define MC_JSON_TYPES_H

typedef enum {
 MJS_TYPE_STRING = 1,
 MJD_TYPE_BOOLEAN = 2,
 MJS_TYPE_NULL = 3,
 MJS_TYPE_OBJECT = 4,
 MJS_TYPE_ARRAY = 5,
 MJS_TYPE_NUMBER_INT = 6,
 MJS_TYPE_NUMBER_FLOAT = 7,
 MJS_TYPE_CONTAINER = 8,
} MJS_TYPE;


typedef enum {
 MJS_RESULT_NO_ERROR = 0,
 MJS_RESULT_NULL_POINTER,
 MJS_RESULT_SYNTAX_ERROR,
 MJS_RESULT_UNEXPECTED_TOKEN,
 MJS_RESULT_INCOMPLETE_BRACKETS,
 MJS_RESULT_INCOMPLETE_DOUBLE_QUOTES,
 MJS_RESULT_ALLOCATION_FAILED, 
} MJS_RESULT;

#define MAX_CACHE_BYTES      512
#define MAX_RESERVE_BYTES    128
#define MAX_RESERVE_ELEMENTS 16
#define MAX_NESTED_VALUE     10
#define MAX_HASH_BUCKETS     16
#endif

